# Generated by Django 4.1.6 on 2023-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebrew', models.CharField(max_length=300)),
                ('english', models.CharField(max_length=300)),
                ('root', models.CharField(max_length=10)),
                ('pos', models.CharField(max_length=10)),
                ('form', models.CharField(max_length=10)),
            ],
        ),
    ]
