# Generated by Django 4.1.6 on 2023-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='example',
            field=models.TextField(default='Temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='note',
            field=models.TextField(default='Temp'),
            preserve_default=False,
        ),
    ]
