# Generated by Django 4.1.6 on 2023-02-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_example_card_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='root',
            new_name='shoresh',
        ),
    ]
