# Generated by Django 4.1.6 on 2023-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_rename_root_card_shoresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
