# Generated by Django 4.1.6 on 2023-02-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
