# Generated by Django 4.1.6 on 2023-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_rename_form_card_binyan_card_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='hebrew_nikkud',
            field=models.CharField(default='temp', max_length=300),
            preserve_default=False,
        ),
    ]
