# Generated by Django 4.1.6 on 2023-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_card_adj_pf_card_adj_pm_card_adj_sf_card_adj_sm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebrew', models.CharField(max_length=300)),
                ('english', models.CharField(max_length=300)),
                ('possible', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
    ]
