# Generated by Django 4.1.6 on 2023-03-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_possibilities_remove_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possibilities',
            name='english',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='possibilities',
            name='possible',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
