# Generated by Django 4.1.6 on 2023-03-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_alter_possibilities_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='possibilities',
            name='english_dict',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='possibilities',
            name='hebrew_dict',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
