# Generated by Django 4.1.6 on 2023-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_possibilities_row_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='row_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
