# Generated by Django 4.1.6 on 2023-03-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0016_card_row_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Possibilities',
        ),
    ]
